
[influxdb]

host = "influxdb.mydomain.com"
port = 8086
user = ""
password = ""
database = "testing"
measurement = "weather"

[FMI]

variables = ["temperature", "pressure", "humidity"]
location = "Kumpula"

