
[influxdb]

host = "influxdb.mydomain.com"
port = 8086
user = ""
password = ""
database = "testing"
measurement = "weather"

[influxdb.tags]

source = "FMI uploader"

[FMI]

delay = 30
history = 20
variables = ["temperature", "pressure", "humidity"]
location = "Kumpula"

